[package]
name = "impulse"
version = "0.1.0"
authors = ["Josh Leverette <coder543@gmail.com>"]

[dependencies]
ws = "0.7.3"
env_logger = "0.5.4"
log = "0.4.1"
lazy_static = "1.0.0"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.10"
